"""Default transactional email templates."""

from __future__ import annotations

DEFAULT_EMAIL_TEMPLATES: list[dict[str, str]] = [
    {
        "slug": "project_created",
        "name": "Project Created",
        "description": "Sent when a new project is created.",
        "subject": "New project {{ToolNumber}} created",
        "body_html": "<p>Hello {{Designer}},</p><p>A new project <strong>{{ToolNumber}}</strong> has been created for {{Customer}}.</p><p>Due date: {{DueDate}}</p>",
        "body_text": "Hello {{Designer}},\n\nA new project {{ToolNumber}} has been created for {{Customer}}.\nDue date: {{DueDate}}",
    },
    {
        "slug": "project_assigned",
        "name": "Project Assigned",
        "description": "Sent when a designer or surfacer is assigned to a project.",
        "subject": "You have been assigned Tool {{ToolNumber}}",
        "body_html": "<p>Hello {{Designer}},</p><p>You have been assigned Tool <strong>{{ToolNumber}}</strong>.</p><p>Customer: {{Customer}}<br/>Due Date: {{DueDate}}</p>",
        "body_text": "Hello {{Designer}},\n\nYou have been assigned Tool {{ToolNumber}}.\nCustomer: {{Customer}}\nDue Date: {{DueDate}}",
    },
    {
        "slug": "project_reassigned",
        "name": "Project Reassigned",
        "description": "Sent when project ownership changes.",
        "subject": "Project reassigned: {{ToolNumber}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Project <strong>{{ToolNumber}}</strong> has been reassigned.</p><p>Customer: {{Customer}}</p>",
        "body_text": "Hello {{Designer}},\n\nProject {{ToolNumber}} has been reassigned.\nCustomer: {{Customer}}",
    },
    {
        "slug": "milestone_assigned",
        "name": "Milestone Assigned",
        "description": "Sent when a milestone is assigned.",
        "subject": "Milestone assigned: {{Milestone}} on {{ToolNumber}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Milestone <strong>{{Milestone}}</strong> on {{ToolNumber}} is assigned to you.</p><p>Due: {{DueDate}}</p>",
        "body_text": "Hello {{Designer}},\n\nMilestone {{Milestone}} on {{ToolNumber}} is assigned to you.\nDue: {{DueDate}}",
    },
    {
        "slug": "milestone_due",
        "name": "Milestone Due Tomorrow",
        "description": "Sent when a milestone is due tomorrow.",
        "subject": "Milestone due tomorrow: {{Milestone}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Milestone <strong>{{Milestone}}</strong> on {{ToolNumber}} is due tomorrow.</p>",
        "body_text": "Hello {{Designer}},\n\nMilestone {{Milestone}} on {{ToolNumber}} is due tomorrow.",
    },
    {
        "slug": "milestone_overdue",
        "name": "Milestone Overdue",
        "description": "Sent when a milestone is overdue.",
        "subject": "Overdue milestone: {{Milestone}} on {{ToolNumber}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Milestone <strong>{{Milestone}}</strong> on {{ToolNumber}} is overdue.</p>",
        "body_text": "Hello {{Designer}},\n\nMilestone {{Milestone}} on {{ToolNumber}} is overdue.",
    },
    {
        "slug": "project_completed",
        "name": "Project Completed",
        "description": "Sent when a project is marked completed.",
        "subject": "Project completed: {{ToolNumber}}",
        "body_html": "<p>Project <strong>{{ToolNumber}}</strong> for {{Customer}} has been completed.</p>",
        "body_text": "Project {{ToolNumber}} for {{Customer}} has been completed.",
    },
    {
        "slug": "timesheet_reminder",
        "name": "Timesheet Reminder",
        "description": "Sent when timesheet entries are pending.",
        "subject": "Timesheet reminder for {{Period}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Please complete your timesheet for {{Period}}.</p>",
        "body_text": "Hello {{Designer}},\n\nPlease complete your timesheet for {{Period}}.",
    },
    {
        "slug": "timesheet_approved",
        "name": "Timesheet Approved",
        "description": "Sent when a timesheet is approved.",
        "subject": "Timesheet approved for {{Period}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Your timesheet for {{Period}} has been approved.</p>",
        "body_text": "Hello {{Designer}},\n\nYour timesheet for {{Period}} has been approved.",
    },
    {
        "slug": "timesheet_rejected",
        "name": "Timesheet Rejected",
        "description": "Sent when a timesheet is rejected.",
        "subject": "Timesheet rejected for {{Period}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Your timesheet for {{Period}} was rejected. {{Notes}}</p>",
        "body_text": "Hello {{Designer}},\n\nYour timesheet for {{Period}} was rejected. {{Notes}}",
    },
    {
        "slug": "historical_import_completed",
        "name": "Historical Import Completed",
        "description": "Sent when a historical import finishes.",
        "subject": "Import completed: {{ImportName}}",
        "body_html": "<p>Historical import <strong>{{ImportName}}</strong> completed.</p><p>{{Summary}}</p>",
        "body_text": "Historical import {{ImportName}} completed.\n{{Summary}}",
    },
    {
        "slug": "password_reset",
        "name": "Password Reset",
        "description": "Sent when a password reset is requested.",
        "subject": "Reset your ProTrack password",
        "body_html": "<p>Hello {{Designer}},</p><p>Use this link to reset your password: <a href=\"{{ResetLink}}\">{{ResetLink}}</a></p>",
        "body_text": "Hello {{Designer}},\n\nUse this link to reset your password: {{ResetLink}}",
    },
    {
        "slug": "welcome_user",
        "name": "Welcome User",
        "description": "Sent when a new user account is created.",
        "subject": "Welcome to ProTrack",
        "body_html": "<p>Hello {{Designer}},</p><p>Your ProTrack account has been created. Sign in at {{LoginUrl}}.</p>",
        "body_text": "Hello {{Designer}},\n\nYour ProTrack account has been created. Sign in at {{LoginUrl}}",
    },
    {
        "slug": "leave_reminder",
        "name": "Leave Reminder",
        "description": "Sent for upcoming leave planning.",
        "subject": "Leave reminder for {{Designer}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Leave is scheduled for {{Period}}.</p>",
        "body_text": "Hello {{Designer}},\n\nLeave is scheduled for {{Period}}.",
    },
    {
        "slug": "low_workload_notification",
        "name": "Low Workload Notification",
        "description": "Sent when a designer has available capacity.",
        "subject": "Available capacity: {{Designer}}",
        "body_html": "<p>{{Designer}} has available capacity next week.</p>",
        "body_text": "{{Designer}} has available capacity next week.",
    },
    {
        "slug": "resource_allocation",
        "name": "Resource Allocation",
        "description": "Sent when resources are reallocated.",
        "subject": "Resource update on {{ToolNumber}}",
        "body_html": "<p>Resources on {{ToolNumber}} have been updated.</p><p>{{Summary}}</p>",
        "body_text": "Resources on {{ToolNumber}} have been updated.\n{{Summary}}",
    },
    {
        "slug": "customer_project_update",
        "name": "Customer Project Update",
        "description": "Customer-facing project update.",
        "subject": "Project update: {{ToolNumber}}",
        "body_html": "<p>Dear {{CustomerContact}},</p><p>Update for project <strong>{{ToolNumber}}</strong> ({{PartDescription}}).</p><p>{{Message}}</p>",
        "body_text": "Dear {{CustomerContact}},\n\nUpdate for project {{ToolNumber}}.\n\n{{Message}}",
    },
    {
        "slug": "progress_update",
        "name": "Progress Update",
        "description": "Customer progress update email.",
        "subject": "Progress update: {{ToolNumber}}",
        "body_html": "<p>Dear {{CustomerContact}},</p><p>{{Message}}</p><p>Status: {{ProjectStatus}} | Stage: {{ProjectStage}}</p>",
        "body_text": "Dear {{CustomerContact}},\n\n{{Message}}\nStatus: {{ProjectStatus}}",
    },
    {
        "slug": "files_released",
        "name": "Files Released",
        "description": "Notify customer that files were released.",
        "subject": "Files released: {{ToolNumber}}",
        "body_html": "<p>Dear {{CustomerContact}},</p><p>Released files are available for <strong>{{ToolNumber}}</strong>.</p><p>{{Message}}</p>",
        "body_text": "Dear {{CustomerContact}},\n\nReleased files are available for {{ToolNumber}}.\n{{Message}}",
    },
    {
        "slug": "delay_notification",
        "name": "Delay Notification",
        "description": "Notify customer of a schedule delay.",
        "subject": "Schedule update: {{ToolNumber}}",
        "body_html": "<p>Dear {{CustomerContact}},</p><p>There is a schedule update for <strong>{{ToolNumber}}</strong>.</p><p>{{Message}}</p>",
        "body_text": "Dear {{CustomerContact}},\n\nSchedule update for {{ToolNumber}}.\n{{Message}}",
    },
    {
        "slug": "meeting_summary",
        "name": "Meeting Summary",
        "description": "Share meeting notes with customer.",
        "subject": "Meeting summary: {{ToolNumber}}",
        "body_html": "<p>Dear {{CustomerContact}},</p><p>{{Message}}</p>",
        "body_text": "Dear {{CustomerContact}},\n\n{{Message}}",
    },
    {
        "slug": "quote",
        "name": "Quote",
        "description": "Send quote details to customer.",
        "subject": "Quote for {{ToolNumber}}",
        "body_html": "<p>Dear {{CustomerContact}},</p><p>Quoted hours: {{QuotedHours}}</p><p>{{Message}}</p>",
        "body_text": "Dear {{CustomerContact}},\n\nQuoted hours: {{QuotedHours}}\n{{Message}}",
    },
    {
        "slug": "quote_ready",
        "name": "Quote Ready",
        "description": "Internal quote ready notification.",
        "subject": "Quote ready: {{ToolNumber}}",
        "body_html": "<p>Quote is ready for <strong>{{ToolNumber}}</strong> ({{QuotedHours}} hours).</p>",
        "body_text": "Quote is ready for {{ToolNumber}} ({{QuotedHours}} hours).",
    },
    {
        "slug": "quote_approved",
        "name": "Quote Approved",
        "description": "Sent when a quote is approved.",
        "subject": "Quote approved: {{ToolNumber}}",
        "body_html": "<p>Quote for <strong>{{ToolNumber}}</strong> has been approved.</p>",
        "body_text": "Quote for {{ToolNumber}} has been approved.",
    },
    {
        "slug": "engineering_change_notice",
        "name": "Engineering Change Notice",
        "description": "Engineering change notice to customer.",
        "subject": "Engineering change notice: {{ToolNumber}}",
        "body_html": "<p>Dear {{CustomerContact}},</p><p>{{Message}}</p>",
        "body_text": "Dear {{CustomerContact}},\n\n{{Message}}",
    },
    {
        "slug": "management_notification",
        "name": "Management Notification",
        "description": "Management and review notifications.",
        "subject": "Management notification: {{ToolNumber}}",
        "body_html": "<p>{{Message}}</p>",
        "body_text": "{{Message}}",
    },
    {
        "slug": "daily_engineering_summary",
        "name": "Daily Engineering Summary",
        "description": "Morning engineering digest for managers.",
        "subject": "Morning Engineering Summary — {{Period}}",
        "body_html": "<p><strong>Morning Engineering Summary</strong></p><p>{{Summary}}</p>",
        "body_text": "{{Summary}}",
    },
    {
        "slug": "weekly_engineering_summary",
        "name": "Weekly Engineering Summary",
        "description": "Weekly performance summary for managers.",
        "subject": "Engineering Performance Summary — {{Period}}",
        "body_html": "<p><strong>Weekly Engineering Performance</strong></p><p>{{Summary}}</p>",
        "body_text": "{{Summary}}",
    },
    {
        "slug": "monthly_engineering_report",
        "name": "Monthly Engineering Report",
        "description": "Monthly engineering report notification.",
        "subject": "Monthly Engineering Report — {{Period}}",
        "body_html": "<p><strong>Monthly Engineering Report</strong></p><p>{{Summary}}</p>",
        "body_text": "{{Summary}}",
    },
    {
        "slug": "project_status",
        "name": "Project Status (Manual)",
        "description": "Manual project status update to stakeholders.",
        "subject": "Project status: {{ToolNumber}}",
        "body_html": "<p>{{Message}}</p>",
        "body_text": "{{Message}}",
    },
    {
        "slug": "customer_update",
        "name": "Customer Update (Manual)",
        "description": "Manual customer update email.",
        "subject": "Customer update: {{Customer}}",
        "body_html": "<p>{{Message}}</p>",
        "body_text": "{{Message}}",
    },
    {
        "slug": "resource_notification",
        "name": "Resource Notification (Manual)",
        "description": "Manual resource notification.",
        "subject": "Resource notification",
        "body_html": "<p>{{Message}}</p>",
        "body_text": "{{Message}}",
    },
    {
        "slug": "project_summary",
        "name": "Project Summary (Manual)",
        "description": "Manual project summary email.",
        "subject": "Project summary: {{ToolNumber}}",
        "body_html": "<p>{{Message}}</p>",
        "body_text": "{{Message}}",
    },
]
