"""Default transactional email templates."""

from __future__ import annotations

DEFAULT_EMAIL_TEMPLATES: list[dict[str, str]] = [
    {
        "slug": "project_created",
        "name": "Project Created",
        "description": "Sent when a new project is created.",
        "subject": "New project {{ToolNumber}} created",
        "body_html": "<p>Hello {{Designer}},</p><p>A new project <strong>{{ToolNumber}}</strong> has been created for {{Customer}}.</p><p>Due date: {{DueDate}}</p>",
        "body_text": "Hello {{Designer}},\n\nA new project {{ToolNumber}} has been created for {{Customer}}.\nDue date: {{DueDate}}",
    },
    {
        "slug": "project_assigned",
        "name": "Project Assigned",
        "description": "Sent when a designer or surfacer is assigned to a project.",
        "subject": "You have been assigned Tool {{ToolNumber}}",
        "body_html": "<p>Hello {{Designer}},</p><p>You have been assigned Tool <strong>{{ToolNumber}}</strong>.</p><p>Customer: {{Customer}}<br/>Due Date: {{DueDate}}</p>",
        "body_text": "Hello {{Designer}},\n\nYou have been assigned Tool {{ToolNumber}}.\nCustomer: {{Customer}}\nDue Date: {{DueDate}}",
    },
    {
        "slug": "milestone_assigned",
        "name": "Milestone Assigned",
        "description": "Sent when a milestone is assigned.",
        "subject": "Milestone assigned: {{MilestoneName}} on {{ToolNumber}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Milestone <strong>{{MilestoneName}}</strong> on {{ToolNumber}} is assigned to you.</p><p>Due: {{DueDate}}</p>",
        "body_text": "Hello {{Designer}},\n\nMilestone {{MilestoneName}} on {{ToolNumber}} is assigned to you.\nDue: {{DueDate}}",
    },
    {
        "slug": "milestone_due",
        "name": "Milestone Due",
        "description": "Sent when a milestone is due tomorrow.",
        "subject": "Milestone due tomorrow: {{MilestoneName}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Milestone <strong>{{MilestoneName}}</strong> on {{ToolNumber}} is due tomorrow.</p>",
        "body_text": "Hello {{Designer}},\n\nMilestone {{MilestoneName}} on {{ToolNumber}} is due tomorrow.",
    },
    {
        "slug": "milestone_overdue",
        "name": "Milestone Overdue",
        "description": "Sent when a milestone is overdue.",
        "subject": "Overdue milestone: {{MilestoneName}} on {{ToolNumber}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Milestone <strong>{{MilestoneName}}</strong> on {{ToolNumber}} is overdue.</p>",
        "body_text": "Hello {{Designer}},\n\nMilestone {{MilestoneName}} on {{ToolNumber}} is overdue.",
    },
    {
        "slug": "project_completed",
        "name": "Project Completed",
        "description": "Sent when a project is marked completed.",
        "subject": "Project completed: {{ToolNumber}}",
        "body_html": "<p>Project <strong>{{ToolNumber}}</strong> for {{Customer}} has been completed.</p>",
        "body_text": "Project {{ToolNumber}} for {{Customer}} has been completed.",
    },
    {
        "slug": "timesheet_reminder",
        "name": "Timesheet Reminder",
        "description": "Sent when timesheet entries are pending.",
        "subject": "Timesheet reminder for {{Period}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Please complete your timesheet for {{Period}}.</p>",
        "body_text": "Hello {{Designer}},\n\nPlease complete your timesheet for {{Period}}.",
    },
    {
        "slug": "timesheet_approved",
        "name": "Timesheet Approved",
        "description": "Sent when a timesheet is approved.",
        "subject": "Timesheet approved for {{Period}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Your timesheet for {{Period}} has been approved.</p>",
        "body_text": "Hello {{Designer}},\n\nYour timesheet for {{Period}} has been approved.",
    },
    {
        "slug": "timesheet_rejected",
        "name": "Timesheet Rejected",
        "description": "Sent when a timesheet is rejected.",
        "subject": "Timesheet rejected for {{Period}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Your timesheet for {{Period}} was rejected. {{Notes}}</p>",
        "body_text": "Hello {{Designer}},\n\nYour timesheet for {{Period}} was rejected. {{Notes}}",
    },
    {
        "slug": "historical_import_completed",
        "name": "Historical Import Completed",
        "description": "Sent when a historical import finishes.",
        "subject": "Import completed: {{ImportName}}",
        "body_html": "<p>Historical import <strong>{{ImportName}}</strong> completed.</p><p>{{Summary}}</p>",
        "body_text": "Historical import {{ImportName}} completed.\n{{Summary}}",
    },
    {
        "slug": "password_reset",
        "name": "Password Reset",
        "description": "Sent when a password reset is requested.",
        "subject": "Reset your ProTrack password",
        "body_html": "<p>Hello {{Designer}},</p><p>Use this link to reset your password: <a href=\"{{ResetLink}}\">{{ResetLink}}</a></p>",
        "body_text": "Hello {{Designer}},\n\nUse this link to reset your password: {{ResetLink}}",
    },
    {
        "slug": "welcome_user",
        "name": "Welcome User",
        "description": "Sent when a new user account is created.",
        "subject": "Welcome to ProTrack",
        "body_html": "<p>Hello {{Designer}},</p><p>Your ProTrack account has been created. Sign in at {{LoginUrl}}.</p>",
        "body_text": "Hello {{Designer}},\n\nYour ProTrack account has been created. Sign in at {{LoginUrl}}",
    },
    {
        "slug": "leave_reminder",
        "name": "Leave Reminder",
        "description": "Sent for upcoming leave planning.",
        "subject": "Leave reminder for {{Designer}}",
        "body_html": "<p>Hello {{Designer}},</p><p>Leave is scheduled for {{Period}}.</p>",
        "body_text": "Hello {{Designer}},\n\nLeave is scheduled for {{Period}}.",
    },
    {
        "slug": "low_workload_notification",
        "name": "Low Workload Notification",
        "description": "Sent when a designer has available capacity.",
        "subject": "Available capacity: {{Designer}}",
        "body_html": "<p>{{Designer}} has available capacity next week.</p>",
        "body_text": "{{Designer}} has available capacity next week.",
    },
    {
        "slug": "resource_allocation",
        "name": "Resource Allocation",
        "description": "Sent when resources are reallocated.",
        "subject": "Resource update on {{ToolNumber}}",
        "body_html": "<p>Resources on {{ToolNumber}} have been updated.</p><p>{{Summary}}</p>",
        "body_text": "Resources on {{ToolNumber}} have been updated.\n{{Summary}}",
    },
    {
        "slug": "quote_approval",
        "name": "Quote Approval",
        "description": "Sent when a quote requires approval.",
        "subject": "Quote approval required: {{ToolNumber}}",
        "body_html": "<p>Quote approval is required for {{ToolNumber}} ({{Customer}}).</p>",
        "body_text": "Quote approval is required for {{ToolNumber}} ({{Customer}}).",
    },
    {
        "slug": "project_status",
        "name": "Project Status (Manual)",
        "description": "Manual project status update to stakeholders.",
        "subject": "Project status: {{ToolNumber}}",
        "body_html": "<p>{{Message}}</p>",
        "body_text": "{{Message}}",
    },
    {
        "slug": "customer_update",
        "name": "Customer Update (Manual)",
        "description": "Manual customer update email.",
        "subject": "Customer update: {{Customer}}",
        "body_html": "<p>{{Message}}</p>",
        "body_text": "{{Message}}",
    },
    {
        "slug": "resource_notification",
        "name": "Resource Notification (Manual)",
        "description": "Manual resource notification.",
        "subject": "Resource notification",
        "body_html": "<p>{{Message}}</p>",
        "body_text": "{{Message}}",
    },
    {
        "slug": "project_summary",
        "name": "Project Summary (Manual)",
        "description": "Manual project summary email.",
        "subject": "Project summary: {{ToolNumber}}",
        "body_html": "<p>{{Message}}</p>",
        "body_text": "{{Message}}",
    },
]
