"""Tables that receive tenant_id in R10 M1 (phase70).

Excludes: tenants (registry), feature_flags (already scoped), currencies (global ISO).
"""

from __future__ import annotations

# Keep alphabetical within groups for review diffs.
TENANT_SCOPED_TABLES: tuple[str, ...] = (
    # Core identity / org / delivery / timesheets
    "activities",
    "background_jobs",
    "compensation_change_requests",
    "contacts",
    "customers",
    "exit_interviews",
    "login_sessions",
    "milestones",
    "notifications",
    "onboarding_checklist_items",
    "onboarding_checklist_templates",
    "onboarding_checklists",
    "org_departments",
    "password_history",
    "performance_review_cycles",
    "performance_review_items",
    "performance_review_projects",
    "performance_review_sections",
    "performance_review_sheets",
    "performance_review_templates",
    "project_saved_views",
    "project_template_milestones",
    "project_templates",
    "project_workstreams",
    "projects",
    "roles",
    "security_policy_settings",
    "stream_skills",
    "streams",
    "team_members",
    "team_membership_periods",
    "teams",
    "ticket_category_routes",
    "ticket_comments",
    "tickets",
    "timesheet_entries",
    "timesheet_entry_deletion_logs",
    "timesheet_import_history",
    "timesheets",
    "user_job_events",
    "user_skill_ratings",
    "user_working_model_periods",
    "users",
    "workstreams",
    # Lookups / settings
    "non_productive_codes",
    "operational_role_types",
    "project_types",
    "task_types",
    "working_models",
    # Foundation
    "branding_settings",
    "company_settings",
    "contact_types",
    "departments",
    "email_messages",
    "email_settings",
    "email_templates",
    "engineering_disciplines",
    "file_path_settings",
    "holidays",
    "notification_settings",
    "skills",
    "user_preferences",
    "user_skills",
    # Finance (not currencies)
    "ai_forecast_placeholders",
    "budgets",
    "company_finance_settings",
    "cost_centres",
    "employee_cost_profiles",
    "expenses",
    "finance_plan_lines",
    "finance_planning_scenarios",
    "finance_plans",
    "fx_rates",
    "project_financial_snapshots",
    "quote_invoice_lines",
    "quote_payment_lines",
    "quote_revisions",
    "quotes",
    "team_commercial_fee_bands",
    "team_commercial_terms",
    # Intelligence / enterprise / training
    "document_assets",
    "engineering_changes",
    "learning_plan_items",
    "learning_plans",
    "legal_entities",
    "lessons_learned",
    "project_decisions",
    "project_knowledge_records",
    "training_assignments",
    "training_courses",
    # Public API / webhooks
    "api_keys",
    "webhook_deliveries",
    "webhook_endpoints",
    # Commercial readiness (R10-010)
    "commercial_signoffs",
    "design_partners",
    "trust_control_checks",
)
